// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKgyu0r9SO7O-8QCqxD3AvAT6bdVOddIY',
    appId: '1:251804242142:web:8c621cdfe8134b5f23324f',
    messagingSenderId: '251804242142',
    projectId: 'mini-health-appointment',
    authDomain: 'mini-health-appointment.firebaseapp.com',
    storageBucket: 'mini-health-appointment.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzzqQc8NMmUFTWPnqeUWOcEPci7WEdRtY',
    appId: '1:251804242142:android:eac9ac67c2a9f30423324f',
    messagingSenderId: '251804242142',
    projectId: 'mini-health-appointment',
    storageBucket: 'mini-health-appointment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZjW2NBjcq5sUAdZO8fZJkMDybbkB395w',
    appId: '1:251804242142:ios:1c1e37edd7fc51f023324f',
    messagingSenderId: '251804242142',
    projectId: 'mini-health-appointment',
    storageBucket: 'mini-health-appointment.firebasestorage.app',
    iosBundleId: 'com.example.miniHealthAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZjW2NBjcq5sUAdZO8fZJkMDybbkB395w',
    appId: '1:251804242142:ios:1c1e37edd7fc51f023324f',
    messagingSenderId: '251804242142',
    projectId: 'mini-health-appointment',
    storageBucket: 'mini-health-appointment.firebasestorage.app',
    iosBundleId: 'com.example.miniHealthAppointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKgyu0r9SO7O-8QCqxD3AvAT6bdVOddIY',
    appId: '1:251804242142:web:ba89a48ab9b7eb3f23324f',
    messagingSenderId: '251804242142',
    projectId: 'mini-health-appointment',
    authDomain: 'mini-health-appointment.firebaseapp.com',
    storageBucket: 'mini-health-appointment.firebasestorage.app',
  );
}
